<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-2PTSSEC5" name="Validating Title(failed)" tests="1" failures="1" timestamp="25 Sep 2020 13:05:26 GMT" time="55.196" errors="0">
  <testcase name="ValidateheaderText" time="0.001" classname="Academy.validateTitle">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Academy.validateTitle.ValidateheaderText(validateTitle.java:44)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ValidateheaderText -->
</testsuite> <!-- Validating Title(failed) -->
